version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://myfirstreactapp00/
      - aws cloudfront create-invalidation --distribution-id E2MBY28H7XED5H --paths '/*'
